### PR TITLE
Bug/250 duplicate keys in player lists

### LINKED ISSUE #250: Player List - Duplicate keys when player’s have the same name
Currently the PlayersList on all host screens use the player’s name as the key for each component, but duplicate keys are issued when two or more players join with the same name. 

Also Setting screen.

The PlayersList should instead use the playerID of each player to retain uniqueness.

### PR DESCRIPTION
**Pull request by wise-king-sullyman**
#### 0. Make sure your issue is linked:

Close #250 

#### 1. Purpose:

1. Refactor PlayerList to not use names as keys
2. Refactor PlayerKicker and OptionList to not use player names as keys
3. Prevent players from using the name of a player currently in the game / staging going forward. 

#### 2. Implementation:

1.
- Swap the players name with finding that players ID and using that as the key
2. 
- Convert OptionList to take an array of objects with a `text` and a `value` rather than just an array of strings. The `text` is the text that should be rendered on the accordion fold, the `value` is what will be passed to the `onItemClick` callback when that fold is clicked. 
- Update PlayerKicker to match this new API.

3. 

- Put the HostContext event handling switch into a thunk to make state accessible from within it.
- Based off of the state conditionally dispatch the `PLAYER_CONNECTED` action as before, or (if the player attempting to join has used the same name as a player already in the game or in staging) dispatch a new `SEND_NAME_TAKEN_MESSAGE` action.
- Add this new action to the HostReducerMiddleware and have it update the `gameState` of the offending player to the new `connection-refused-name-taken` state.
- Update `PlayerScreenController` to inform the offending player that they have been refused access to the lobby when this state is received, and explain why they were refused using the `PlayerErrorScreen` with some snark baked in for flavor. 

#### 4. How to Test:

0. Fetch my branch and switch to it
1. Start the application backend then frontend
2. Open at least three browser windows
3. Select host mode on one and join on the others
4. Attempt to use the same name for both players
5. Verify that you are not able to join the lobby using the name of a player already in staging
6. Verify that you *are* able to join the lobby using a name not yet in use
7. Start the game
8. Open another browser window and select join mode again
9. Attempt to join using the name of one of your players already in the game
10. Verify that you are not able to join the lobby using the name of a player already in the game
11. Verify that you *are* able to join the lobby using a name not yet in use
12. Using dev tools verify that the PlayerList and PlayerKicker are using playerId as the key now rather than name 

#### 5. Cleanup
- [x] I've added all TODOs needed
- [x] I've removed all unneeded comments
- [x] I've updated the snapshot tests and checked to make sure they're accurate if they changed
- [x] I've removed all unnecessary `console.log`s

### CODE REVIEW

File: frontend/src/contexts/HostContext/HostContext.js [hunk 1]
```diff
@@ -44,50 +55,61 @@ function HostProvider({ children }) {
...
+          });
+
+        case 'socket-connection-error':
+          dispatch({ type: 'UPDATE_JOIN_CODE', payload: { lobbyID: 'ERROR' } });
+          return setSocketHasError(true);
+
+        default:
+          return undefined;
+      }
+    };
```
Comment (wise-king-sullyman) [inline frontend/src/contexts/HostContext/HostContext.js:103]: Note to make reviewing easier: this change section is just from moving the switch into the thunk and I didn't *really* change anything here.

File: frontend/src/contexts/HostContext/HostContext.spec.js [hunk 2]
```diff
@@ -141,136 +141,342 @@ describe('Context', () => {
...
+        act(() => {
+          eventHandlers.message({
+            event: 'player-connected',
+            payload: { playerId: 'TEST', playerName: 'TESTER' },
+          });
+        });
+
+        expect(screen.queryAllByTestId('player-staging').length).toBe(1);
+      });
+
```
Comment (wise-king-sullyman) [inline frontend/src/contexts/HostContext/HostContext.spec.js:182]: Note to make reviewing easier: I didn't change anything here other than the test name for matching my update and moving it into another describe block to group all of these (now many) `player-connected` related tests together.

File: frontend/src/contexts/HostContext/HostContext.spec.js [hunk 3]
```diff
@@ -141,136 +141,342 @@ describe('Context', () => {
...
+          recipients: ['TEST'],
+          payload: {
+            gameState: 'connected',
+            message: {
+              big: 'Attempting to join lobby',
+              small: 'Please wait',
+            },
           },
-        },
+        });
```
Comment (wise-king-sullyman) [inline frontend/src/contexts/HostContext/HostContext.spec.js:439]: Note to make reviewing easier: I didn't change anything here other than moving it into another describe block to group all of these (now many) `player-connected` related tests together.

File: frontend/src/contexts/HostContext/HostContext.spec.js [hunk 4]
```diff
@@ -141,136 +141,342 @@ describe('Context', () => {
...
+            gameState: 'connected',
+            message: {
+              big: 'A round is in progress',
+              small: 'You will join the next round automatically',
+            },
+            removeLoading: 'joining-lobby',
           },
-          removeLoading: 'joining-lobby',
-        },
+        });
```
Comment (wise-king-sullyman) [inline frontend/src/contexts/HostContext/HostContext.spec.js:479]: Note to make reviewing easier: I didn't change anything here other than moving it into another describe block to group all of these (now many) `player-connected` related tests together.

File: frontend/src/contexts/HostContext/hostReducerMiddleware.js [hunk 5]
```diff
@@ -21,6 +21,17 @@ function sendPlayerConnectedMessages(payload) {
...
+  socketInstance.sendMessage({
+    event: 'update',
+    recipients: [payload.playerId],
+    payload: {
+      gameState: 'connection-refused-name-taken',
+      removeLoading: 'joining-lobby',
+    },
+  });
+}
+
```
Comment (sher-s7) [inline frontend/src/contexts/HostContext/hostReducerMiddleware.js:34]: In the future maybe we could make this message appear in a modal so the user can just tap out of it and adjust their name without needing to click Join and enter the code again

File: frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js [hunk 6]
```diff
@@ -42,6 +42,14 @@ export default function PlayerScreenController() {
...
       );
 
+    case 'connection-refused-name-taken':
+      return (
+        <PlayerErrorScreen
+          bigText="That name is already taken"
+          smallText="Try and be creative next time"
+        />
+      );
+
```
Comment (sher-s7) [inline frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js:52]: In the future maybe we could make this message appear in a modal so the user can just tap out of it and adjust their name without needing to click Join and enter the code again

**Review by sher-s7 — DISMISSED** [review]
Really good stuff 👌

File: frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js (hunk 6 above)
Comment (wise-king-sullyman) [reply frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js:52]: I'm looking into this as I really like it as an idea. I think I could add a modal to the player join screen. But (I think) it would require removing the automatic players screen change for `pending-connection` on submit to do it which wouldn't be a *great* experience for people with slow connections.

That being said I think I've got figured out how to do this and will be looking at it more tomorrow.

Comment (wise-king-sullyman) [reply frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js:52]: @I3uckwheat what are your thoughts on this? Do you think keeping the join code inputted is a better feature than having the player's screen change as soon as they hit submit?

File: frontend/src/contexts/HostContext/HostContext.js [hunk 7]
```diff
@@ -35,6 +35,17 @@ const initialState = {
 
 export const HostContext = createContext();
 
+function allNamesUppercase(currentState) {
```
Comment (I3uckwheat) [inline frontend/src/contexts/HostContext/HostContext.js:38]: This sounds like a variable name, not a function name. Functions *do* something.

maybe: "uppercaseAllNamesInState"

Comment (I3uckwheat) [reply frontend/src/contexts/HostContext/HostContext.js:38]: We could probably use a `some` operation instead to make what this is doing more clear.

File: frontend/src/contexts/HostContext/HostContext.js [hunk 8]
```diff
@@ -44,50 +55,61 @@ function HostProvider({ children }) {
...
-
-      default:
-        return undefined;
-    }
+  function createMessageHandler(currentState) {
+    return ({ event, payload, sender }) => {
+      switch (event) {
+        case 'player-connected': {
+          if (
+            allNamesUppercase(currentState).includes(
```
Comment (I3uckwheat) [inline frontend/src/contexts/HostContext/HostContext.js:63]: We could probably just use a .some here:

```
const allPlayers = [...Object.values(state.players), currentState.newPlayerStaging]
const isPlayerNameTaken = allPlayers.some(player => player.name.toUpperCase() === payload.playerName.toUpperCase());
```

isPlayerNameTaken will be true or false

File: frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js (hunk 6 above)
Comment (I3uckwheat) [reply frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js:52]: This is definitely not in scope for this, but something that should be done at a later time.

**Review by I3uckwheat — CHANGES_REQUESTED** [review]

File: frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js (hunk 6 above)
Comment (I3uckwheat) [reply frontend/src/screenControllers/PlayerScreenController/PlayerScreenController.js:52]: This is definitely not in scope for this, but something that should be done at a later time.

File: frontend/src/contexts/HostContext/HostContext.js (hunk 7 above)
Comment (wise-king-sullyman) [reply frontend/src/contexts/HostContext/HostContext.js]: (Effectively) resolved in 541bd19

File: frontend/src/contexts/HostContext/HostContext.js (hunk 8 above)
Comment (wise-king-sullyman) [reply frontend/src/contexts/HostContext/HostContext.js]: Resolved in 541bd19

**Review by I3uckwheat — APPROVED** [review]
